[package]
authors = ["Doug Anderson <DougAnderson444@peerpiper.io>"]
categories = ["network-programming"]
description = "Utilities for WebRTC in libp2p"
edition.workspace = true
license = "MIT"
name = "libp2p-webrtc-utils"
repository = "https://github.com/libp2p/rust-libp2p"
rust-version = { workspace = true }
version = "0.4.0"
publish = true

[dependencies]
asynchronous-codec = { workspace = true }
bytes = "1.10.1"
futures = { workspace = true }
hex = "0.4.3"
libp2p-core = { workspace = true }
libp2p-identity = { workspace = true }
libp2p-noise = { workspace = true }
quick-protobuf = "0.8.1"
quick-protobuf-codec = { workspace = true }
rand = "0.8.5"
serde = { version = "1.0.228", features = ["derive"] }
sha2 = "0.10.9"
tinytemplate = "1.2.1"
tracing = { workspace = true }

[dev-dependencies]
hex-literal = "1.0.0"

[lints]
workspace = true
