[package]
name = "keygen"
version = "0.1.0"
edition.workspace = true
authors = ["demfabris <demfabris@gmail.com>"]
license = "MIT"
repository = "https://github.com/libp2p/rust-libp2p"
keywords = ["peer-to-peer", "libp2p", "networking"]
categories = ["network-programming", "asynchronous"]
publish = false

[package.metadata.release]
release = false

[dependencies]
clap = { version = "4.5.49", features = ["derive"] }
zeroize = "1.8.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
base64 = "0.22.1"
libp2p-identity = { workspace = true }

[lints]
workspace = true
