[package]
name = "libp2p-websocket"
edition.workspace = true
rust-version = { workspace = true }
description = "WebSocket transport for libp2p"
version = "0.45.2"
authors = ["Parity Technologies <admin@parity.io>"]
license = "MIT"
repository = "https://github.com/libp2p/rust-libp2p"
keywords = ["peer-to-peer", "libp2p", "networking"]
categories = ["network-programming", "asynchronous"]

[dependencies]
futures-rustls = { workspace = true, features = ["ring"] }
either = "1.15.0"
futures = { workspace = true }
libp2p-core = { workspace = true }
libp2p-identity = { workspace = true }
parking_lot = "0.12.5"
pin-project-lite = "0.2.16"
rw-stream-sink = { workspace = true }
soketto = "0.8.1"
tracing = { workspace = true }
thiserror = { workspace = true }
url = "2.5.7"
webpki-roots = "1.0.3"

[dev-dependencies]
libp2p-tcp = { workspace = true, features = ["tokio"] }
libp2p-dns = { workspace = true, features = ["tokio"] }
libp2p-identity = { workspace = true, features = ["rand"] }
tokio = { workspace = true, features = ["rt", "macros", "io-std", "io-util"] }
rcgen = { workspace = true }

# Passing arguments to the docsrs builder in order to properly document cfg's.
# More information: https://docs.rs/about/builds#cross-compiling
[package.metadata.docs.rs]
all-features = true

[lints]
workspace = true
