name: Code Coverage

permissions:
  contents: read

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  
jobs:
  coverage:
    runs-on: ubuntu-latest

    env:
      RUSTFLAGS: "-Cinstrument-coverage -Clink-dead-code -Coverflow-checks=off"
      LLVM_PROFILE_FILE: "coverage/%p-%m.profraw"

    steps:
    - uses: actions/checkout@v4

    - name: Set up Rust with coverage tools
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        components: llvm-tools-preview

    - name: Install grcov
      run: |
        curl -LsSf https://github.com/mozilla/grcov/releases/download/v0.8.19/grcov-x86_64-unknown-linux-gnu.tar.bz2 | tar xj
        sudo mv grcov /usr/local/bin/

    - name: Run tests with coverage
      run: |
        cargo clean
        cargo build --tests
        cargo test
        
    - name: Generate coverage report
      run: |
        mkdir -p coverage
        grcov . \
          --binary-path ./target/debug/ \
          --source-dir . \
          --output-type lcov \
          --branch \
          --ignore-not-existing \
          --ignore "/*/.cargo/**" \
          --ignore "target/**" \
          --output-path coverage/lcov.info

    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v2.3.6
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      with:
        path-to-lcov: coverage/lcov.info